### ISSUE TITLE
v0.4.3 (android) - No icons for rewards on ending song screen 

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#114] opened 2023-08-28 07:38 UTC
![Screenshot_2023-08-28-09-36-01-19_e65191035490e46cdbaadce7822066c9.jpg](https://github.com/Xele02/UMO/assets/99509414/ac04dbb9-9bc3-47ff-8c03-27dec7dac8f6)

**Comment by Xele02** [comment] 2023-08-28 16:03
Duplicate of #110

**Closed by Xele02** 2023-08-28 16:03 UTC
