### ISSUE TITLE
v0.4.2 Home diva T pose

### ISSUE THREAD

**Issue by Kilarn** [Xele02/UMO#98] opened 2023-08-25 10:05 UTC
Going into diva menu, exploring it and going back on the home menu lead to T pose for the hope diva

![Screenshot_2023-08-24-16-53-31-95_e65191035490e46cdbaadce7822066c9](https://github.com/Xele02/UMO/assets/99509414/d65eb2fc-2f29-4006-9d9a-ef8ce56ec264)

**Comment by Xele02** [comment] 2023-08-25 16:07
Duplicate of #96

**Closed by Xele02** 2023-08-25 16:07 UTC
