### ISSUE TITLE
Song Selection Does Not Remember Last Played

### ISSUE THREAD

**Issue by Tiger1970prod** [Xele02/UMO#144] opened 2023-11-20 17:39 UTC
The Game Will Default To 小白竜 (Shao Pai Long) so it doesn't matter what song you last played. It will go back to this one song and you'll have to scroll back to the last played. 

Platform: PC (Possibly Android)

https://github.com/Xele02/UMO/assets/80795510/240d53c9-b1a9-4b78-b90c-714912bb73b6

**Comment by Xele02** [comment] 2023-12-06 18:29
I tried but couldn't reproduce this bug either in editor or phone. 
Do you have some filter enabled in the music song selection ? 
If possible I would be interested if youcan upload this file which contain the filters setup : Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/SaveData/save.bin

**Comment by Tiger1970prod** [comment] 2023-12-07 00:06
> I tried but couldn't reproduce this bug either in editor or phone. 
> 
> Do you have some filter enabled in the music song selection ? 
> 
> If possible I would be interested if youcan upload this file which contain the filters setup : Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/SaveData/save.bin

Where would one find that for Unity Editor on Desktop?

**Comment by Xele02** [comment] 2023-12-07 18:25
For windows, I think it should be in
%appdata%/../Local/UtaMacrossOffline/
Or one of the other 2 directory in %appdata%/../
(%appdata% is a shortcut to C:/Users/<yourname>/AppData/

**Comment by Xele02** [comment] 2024-02-02 19:30
Since 0.9.1, I added some log. So if you want to help, activate the logs, go in the song selection, select a song, then reproduce the bug by going somewhere and going back in the selection menu where the song will not be selected anymore. Then send me the log.

For enabling the log : Enable in the UMO Option popup debug and error logging. It will write the log in Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/Log.txt or équivalent in pc in %appdata%/../Local/UtaMacrossOffline/

**Comment by Tiger1970prod** [comment] 2024-07-02 23:04
> Since 0.9.1, I added some log. So if you want to help, activate the logs, go in the song selection, select a song, then reproduce the bug by going somewhere and going back in the selection menu where the song will not be selected anymore. Then send me the log.
> 
> For enabling the log : Enable in the UMO Option popup debug and error logging. It will write the log in Android/data/com.UtaMacrossOffline.UtaMacrossOffline/files/Log.txt or équivalent in pc in %appdata%/../Local/UtaMacrossOffline/

Log: https://drive.google.com/file/d/1Mcp9_0jSfYFqniM52HZErXBiO4olecOo/view?usp=sharing

**Comment by Xele02** [comment] 2024-08-25 11:22
I fixed something else, could also fix this. To check in next release.

**Comment by Xele02** [comment] 2024-09-22 16:22
Closing as there is nothing new

**Closed by Xele02** 2024-09-22 16:22 UTC
